services:
    - docker

env:
    - secure: "OZjVo7CKTPNgcy2LKAS3S35KmbOGZ7B9su+ftmO6JFSRMIKTGEpjeHSNVO1tUvsQzawOakoRLrSuU6cfJBpgC1cbinuM+ItwdDl6UsIyG9/1BKGx1DHDZFBIXSWmxBIbmochQZlmkGEBEIcmxwbfJjfUF7m7S3X0nDJBVEnXl9sL48hQlcPZvVP4qOU/yaK72NJ5GFq2KvmpTDPNsyfW2sX9GZyb9y4w7Ny9Mfs7YfGT2Nf/0tfNT5UCM4VF5B3OdEF5ovmMwuSE1al2iTmTTHWQwOZ7TiWWUCpmHuVS8M7MDc1ZvwS4jeoIm36MWAdVu/mjxhbKGdYJvdee8aYuhe4pF9vZTrXTNKR/Msc77DLeh1qPop84zyAx3vbr9LHzQ/MMVCA04aADDlm7pABaFlQHRV+l8BpFcHmsvRALrgkm7gcJfVpb+FeM4S0YJF1gLZjDh2HuRx00eJmeZJb2VvsfN70Uhw1eHsKGSoL77qCdmeKcEBNEp+Sejm16shpUfs4tpIlFz7OVbCKwXD9t0FEmCcM+9grBoIjQYdq0XGQawEgAMEEDLuIrfWoQkb7KMJDM/lg9wWgIb8c3oUviPA/EwIahvL7Wl/SJET/KSXV1FO1LcomzpIofDY6hYpcmeakcAyzC20oaOLaViqlkODiu8fIMqxj9xl3dNua9EWQ="
before_install:
    - docker build --target test --tag todo-app:test .

script:
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/unit
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/integration
    - docker run --env TRELLO_API_KEY=TRELLO_API_KEY TRELLO_API_SECRET=TRELLO_API_SECRET  --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/end_to_end