services:
    - docker
env:
    global:
        - DOCKER_USERNAME=beckycarter
        - DOCKER_IMAGE_NAME=todo-app
        - secure: "SCc0bbIw13x5uLj6kyHx5A5qhKmzU9oYD87KgfOtXck6utsyhT8CD4kZIx449XOyT/32FG/HW28xZ4x48riV6ifldbtXFUR+I2JTll1+IWTA6HDY2M4jHtkfEIU1KIo4aJVWd/JHqGsmSq7YYTX1ItjZDFJT2sjEbn6Lrg2q+hQEl0/VqzUBQFoiEwuvOt8ieLFnHlSnGSBgaFaqHamr5q5SHINv1bS0bAGot9zUONaEwq0nL+xA1JiqI0q1CRtSWINPjmJRBfe93NtRJ5zDMJuZLctJ57G9q7+9BbAb0+hvH7qfxGeMIUcDPEU7qPJww2h+3/Y+59ZRxxG6Az20kEj/sQL/5R6u5aJDQ/A54zLrvjkvbWV0c4XHqC7l2Yy66jkNyUkh/nrkaAPruRFsD0Q1eOrfPicvDgu8kclf/UgvcE5fhyJu+J8ps3QSKk8rBDoDPr4AhfbKUTH4/1FbkT3662gm0YHZwqltVLtPUvFVjVqqEkd4w9vHUAuykyTeXgUh7ainm+IVxg7NxdraqkV5Ef4+TTtBcjbCJnaVifmAikCtWRV0Sn5cMbd9kWccgbbZ9W7bw1/TJVvBgtnPct8bpzoAx5Uv8x1AlqXtj719a2dNAdFp5gHaAFQGkMtkOSgQ8fNsZBGqrYN+/FmXKOCFjZ+prdbn1A0PVG1nL6A="
install:
    - echo install
    # - docker build --target test --tag todo-app:test .

script:
    - echo script
    # - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/unit
    # - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/integration
    # - docker run -e TRELLO_API_KEY -e TRELLO_API_SECRET --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/end_to_end
    
before_deploy:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
deploy:
    provider: script
    script:  bash scripts/deploy.sh
    on:
      branch: module_8
