services:
    - docker
env:
    global:
        - DOCKER_USERNAME=beckycarter
        - DOCKER_IMAGE_NAME=todo-app
        - HEROKU_USERNAME=becky.carter@softwire.com
        - HEROKU_APP_NAME=beccar-todo-app
        - MONGO_USERNAME='travis_user'
        - MONGO_DEFAULT_DB='todo_app'
        - secure: "jviA0goG/jB5OkP2rMdOJmNUjJksvLYYGhM1DaOX1BoygTNiH/5oU6VQQJNw1ZamnYaS9lYt7Z/581G1TYnz3d2didn1L0FW60l9xw8e/lm0ScNGrI50PEqWRMm9TCn/keAmcdO7/KgRaYnDU5+5S+Z0tvHP71boNFZDbnj6bqI1fM1qJtg5Ju/s4KkGuZx5IAJUPJJg35uaF6KkFDhu+AeAhxQDw0jfLPBb7TVp9MKL37/ei6CoErlpU21OjvROR10Dkx9SWS8qyX9k2t4HZgWrfj3m80+GhTREsXRVL+YbOhFvWrIjjtD+SUG2BjJ5FLlXOAlJJHnOyPCRG9iEeEQpti4eYZ7X+fZDcmXxTt8nXFpTakITrRSRzg4g9+kACybg7jRIwssyMt25lNTaXLmUenvyJq7LWxRnVZTO6mHSwa2y5jWqz5WoHDSUBIGctWCSsOFXIA1Cwepjdo/8p38mi+F9di/OW8QckZViinRlWLpqPGjK0rwSVjtapPFJn78SPCTPnYFinmF4Ub4Syv2c2YwHL7Tg+LOEr8VIlaRsmX0xrZND/nfrDGbmk3tv9U3sA/CqOyZtXPIP+z5DKX7/FeJkFHFXzITi6Ab2PBFZ+w+kb+QEmAcbYWlx/E45hVJXZNLAoKCmLaV9IEI4PRP2Oa3bYZphsyn/rgSG97k="
install:
    - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
    - docker build --target test --tag todo-app:test --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_NAME .

script:
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/unit
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/integration
    - docker run -e MONGO_USERNAME -e MONGO_PASSWORD -e MONGO_URL -e MONGO_DEFAULT_DB --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/end_to_end
    
before_deploy:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
    - heroku container:login
deploy:
    provider: script
    script:  bash scripts/deploy.sh
    on:
      branch: master
