services:
    - docker
env:
    global:
        - DOCKER_USERNAME=beckycarter
        - DOCKER_IMAGE_NAME=todo-app
        - MONGO_USERNAME='travis_user'
        - MONGO_DEFAULT_DB='todo_app'
        - secure: "OpfT3rQxl14I2bbokQ7uPRkCeTqSZ6SaqHHln1gsi7j6IdICZVNo6WpfGJqH8gMp1XS1S159trtarMo8avwnXA1i2ylaf1pf60Fkntt3jGJFX7B3r8J6bgc+5Q1YnBK1C+GSDWCRf+nKJtzb6T2VE2FzjCuZ4Ueeohp+eMVxjBYRL2sGptQxf2LCDbop0lxVdoPaUuPNR7798E98L2vGQJgwC/n0TqNm73RZB2S+PBSc+OAX72aU6LzVM4fLoboXMB7U7R1ATxlWWh/12yAqON0G7yFIivJAOAQArKgR/NzwJFB7G8jMJKcPYC0hjD7Qf6+sQuA+edi2mE4B0Yn1mPdsFg5lQYQ1SfCarpm89UNRNCGC1ZD+o915xGUCcOGggCvvgsuiDkdJ05ezwI1Bfh8Vq+rT3gunWHovjvujiTemm6KI2nMBxCC+1kHwXWZd7JP/5iiGd61E7HdhXAAre5hA6bFAFT84te3ObFof1hcu4IE/jprWytdQfe2WLncDIefESW50lavr2u2Ufd36ncs0GmcG8YLO2ZxcLC0Dx8bD4dsESjob8WtFjy89ddduSMBzLSrgx0w2Eg6/YSmCDTN5+2BP2SB1Jmn9NfBgDeZcZSrMwnQJs4/WbWzAUJcAo7waRtpi50EFNXCGgFH+9rQ+ZArHKkNMBxn1JzoIHMY="
install:
    - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
    - docker build --target test --tag todo-app:test --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_NAME .

script:
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/unit
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/integration
    - docker run -e MONGO_USERNAME -e MONGO_PASSWORD -e MONGO_URL -e MONGO_DEFAULT_DB --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/end_to_end
    
before_deploy:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
deploy:
    provider: script
    script:  bash scripts/deploy.sh
    on:
      branch: main
