services:
    - docker
env:
    global:
        - DOCKER_USERNAME=beckycarter
        - DOCKER_IMAGE_NAME=todo-app

jobs:
    include:
        - stage: test
          env: 
            - MONGO_USERNAME='travis_user'
            - MONGO_DEFAULT_DB='todo_app'
            - secure: "ZVATQHFn/vJrhTS77UNrNg7K5+5+Pgz0zOUZ/JwlRmJiEL2Gc5y++CPt3Qq+T9GvbaiWbCUQIUNKYC/jRjUxcxMjbImn4RHDgUGYtqTBtIh3YbK1A0/LOzjWxdqnTEjZ7q6dHV3iP3OFysQOZwk/om2QuI6n320HMhADzl5LUGoDjKF6W+/jycEYo6+9pH8GyM+TntEZlpvQKnPEj6RSwWCHrgUtlu1F3iUN4XHxJSQIPp0cToQQo3/cPsyy/d3sBGQ4YRWJysJEtfZF28sjwI3sxX7GwGAhn8ap+x/PacP/A+au1KorNAnlI1pUfIm9Wn08FQJUCOWh2MXkjdsSY+5bbNeB+nJEha3uDrINWqV/hXPUgwya/CessPZikTfEwFfd23HUCPj0T/EUOscNmrja/PsUVwr+99oZWubsDhMErT/3qdRd7WSJcN/tl1Nery+MKZRa2rvDsTeRBbsLV+RKP0Q17hfGQM96h6V37fNTMsuAjb6cHaXi88J10B8APydizlxE2cX0mRrLSfFBYtvjQytmjWcM/jVyl5wjo5WmSUOhlYMyyyhj+ajxtj6BMMXstLWXx0tCNxXM0ybhZ1wNm+rEl4E7lhbIKLAf0vb4cNBJrTeg4LUMyZ8r918peaVvNh/lcY7PE2kahI1NVeC1SVcoLacuJIF7sJRgYCM="
          install:
            - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
            - docker build --target test --tag todo-app:test --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_NAME .

          script:
            - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/unit
            - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/integration
            - docker run -e MONGO_USERNAME -e MONGO_PASSWORD -e MONGO_URL -e MONGO_DEFAULT_DB --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/end_to_end

        - stage: release
          if: branch = main
          env:
            - TF_VERSION=0.14.7
            - TF_VAR_prefix='prod'
            - TF_VAR_github_auth_client_id='c71c5ae68c2baaf32915'
            - secure: "Ia+thzEyITr2TVgt5BimiR3FzpJ5YoNHQYT03xUCIwGAZvq45bUYgzfcPccMpV6X4j+2A1tBu3trIK8kutm4Ffwc2citQZJibc2i5+kfqsygYV7JM72tr3FVUVeq32Wnyg2QdLMn23I3q1CEFFv84U3h1v1YXvvtq6l5HFkUEimFCj1xCjtSz8h0ke+1hcrVfWQCUpyqB+j1vETqiYbkaHLHvyuGJkNvjUK9OnT9vS5S0DLvS7EuhTi1knL0qGMWgc4NQxWIycDF4VhcsZsjszmylYrC1UrEf8s1HpzsqyAw3k11gPwT1jwZdWjyvVzvu9L9h7Ka9D5Gle0NkQGV5+Tq3OyvGp4HJrL3jcpj5iT647gvhdrPwGOpGvfPKgH3uV1+l0kz+Q+S7mTxJGsJHYGL2m/kIRIKmbn9DtHJ40RkpZ3LgTz41rm/svkGSKOIVX5JA+paMB+c119Tkm9g1Q3BLqNK5Bd4EzvDpkVy3fo8ubEn9ppmE2VpGRYtOAaoqEu3SAYgIK1uTYFwHgqfKwpbPwle96iDj1+D8cadrtwPpDDuYT54qonmtJOMdtGsXRdgiN3HTlor0NpZYn33CCOvsg3BuJSeIZNrgFuvH15wPzaNcVe+7PTcmxcNZKr2z73pYuUlQiCTIVo+xW6EMAKStDCICPUkdjfEJnkaWjQ="
            
          install:
            - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
            - unzip terraform_"$TF_VERSION"_linux_amd64.zip
            - sudo mv terraform /usr/local/bin/
            - rm terraform_"$TF_VERSION"_linux_amd64.zip
            - terraform init

          script:
            - chmod +x ./scripts/docker_entrypoint_prod.sh
            - docker build --target production --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest --tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest --tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT .

          before_deploy:          
            - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            - terraform apply -auto-approve
            
          deploy:
            skip_cleanup: true
            provider: script
            script:  bash scripts/deploy.sh
