services:
    - docker
env:
    global:
        - DOCKER_USERNAME=beckycarter
        - DOCKER_IMAGE_NAME=todo-app
        - HEROKU_USERNAME=becky.carter@softwire.com
        - HEROKU_APP_NAME=beccar-todo-app
        - MONGO_USERNAME='main_user'
        - MONGO_DEFAULT_DB='todo_app'
        - secure: "mQ0SiVwfJ9gwF8gG7ObQl/KsQlCbAV2PMItSM6YgSZ9gf6hE3mjTIaPGts3Hb/O8e2q6s/I13QJ4TbIK4IPWJOUY4T+QDu/b17LFbz4OKJ2ZgTrSLU1sfpfIvDsb3bv+/dQR6bSAIqv+O9XP7kyE0NwEmhF7al8zYoSMvFl9IrwFtoxVz/F5zOvKTCh80zuk7hVcSr7YBOQrNKtx/04Q7ngVkEQQW+fWkU+bvv4mNqRYGzX/WjRe5c8DZqa01pHZpR5B3D/yketiWbPTeCLR42wzIENo6mGg74vXBV3jW7lpRkOSGGQ/t6MSo7yE2Eo/jIJZgYq6EcUg94CumYdjKiIYDaRWiIZ3tFrtA/eFkGhJh7VvAse17noVzfLLntseq95z6W2z6aQwsgAqLR1Lux5NmkRw9eswx8Ry1N/dsya2BHCqG/hjwX9VlxuN4mMhm0/ciy7PWblOpLMN6SLq+l4N8sc8eGcddZ1kE6vVxXLOeInGCA4xXHSF9spdr1ykL5NDK9CwOUUPRNWnAYcjydxQln2sN41hgGbmqHWpwouD2vqmFefqLEbKOGUoyOOb3N9jlxFPOa1im5r5H1CkHP6VaG76YnX+9YyXNDv8DPZLmiLia3BDxK8z7eEjk7XkRG7hmrWAASjwxI7+yVltiVgw7nzvB4ggkYKropU7y2M="
install:
    - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
    - docker build --target test --tag todo-app:test --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_NAME .

script:
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/unit
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/integration
    - docker run -e MONGO_USERNAME -e MONGO_PASSWORD -e MONGO_URL -e MONGO_DEFAULT_DB --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/end_to_end
    
before_deploy:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
    - heroku container:login
deploy:
    provider: script
    script:  bash scripts/deploy.sh
    on:
      branch: module_9
