services:
    - docker
env:
    global:
        - DOCKER_USERNAME=beckycarter
        - DOCKER_IMAGE_NAME=todo-app
        - HEROKU_USERNAME=becky.carter@softwire.com
        - HEROKU_APP_NAME=beccar-todo-app
        - MONGO_USERNAME='travis_user'
        - MONGO_DEFAULT_DB='todo_app'
        - secure: "Lz1CWRut3rZ/2pvbIIueVnHvXbhIKGHKSCOf+FG8BPHXZ2yDBc8Vp7am1HMf/yE7UdBZihWI9pWMFED68eiI2Kc21CV61XxvFwrgmsXCSTrmiUxJGueGkKlaWDPehl8e8b3WQO/sXnvv5z7R4jjUIIQjUbbZsrzq9+lCkNBBMqo3Bw1gb9e4d2H7F2CNQWH5O1+61H1VX5Ns3AewUFI+0Fs4EhhYINvP7VPeOWA7V7fMJYAX+jYNVyb9GWU6hHCq5tJ1h55yI8B86ND6IkG/P5Cr5eBWpWM8OHRG1aHSFo7JPJi0QFkYX8byWutspIL2H95EwAyaOfPEJ6Pxqjy5bE6F3OWHh7xoZhjUMLfBiZfPi5/5Xx6rqc5CEe1qIVJzNvM5SyVG6jZAPPhlwP1WX0ELAl1PlH7IVYc2C636lC1x+dR8oLhw4QU5iiBm7iw3ZMeeqerN7i91K+qrkM+NmMko2edqY4urwSfblu2GyYjoTzBYFchZgTjb+cyVnXMVbv5DheRc8GHQCoFP52FxBCy/VPz+05zCW1HYKAAIzuHCnaL7p7xsmgYgJiNv3CIc1lSs/cUa+GraD8MyueFYzkv2zWm9tUTxyvaUTfTt0vE3dIxC1OBvQvEKuqupsJ7j00L5UPkMzFsTCt+5L/t4qhSSYAPa8IRpmDgfnHqE+MY="
install:
    - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
    - docker build --target test --tag todo-app:test --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_NAME .

script:
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/unit
    - docker run --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/integration
    - docker run -e MONGO_USERNAME -e MONGO_PASSWORD -e MONGO_URL -e MONGO_DEFAULT_DB --mount type=bind,source="$(pwd)",target=/app todo-app:test tests/end_to_end
    
before_deploy:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
    - heroku container:login
deploy:
    provider: script
    script:  bash scripts/deploy.sh
    on:
      branch: master
